services:
  db:
    image: mongo:7
    volumes:
      - ./data/db:/data/db
  steam:
    build:
      context: .
    network_mode: "service:db"
    volumes:
      - .:/workspace
      - ./bundle:/usr/local/bundle
    depends_on:
      - db
    working_dir: /workspace
    command: bash
