name: Continuous integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci_validation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0']

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name mongo_container

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install imagemagick (convert)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1

      - name: Test
        run: bundle exec rspec
